// <auto-generated />
namespace PhoneStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Update_UserNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_UserNew));
        
        string IMigrationMetadata.Id
        {
            get { return "201911011711327_Update_UserNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
