CREATE TABLE "USERS" (
	"UserID" NUMBER(10,0) NOT NULL,
	"Username" VARCHAR2(50) NOT NULL,
	"Password" VARCHAR2(50) NOT NULL,
	"Role" VARCHAR2(50) NOT NULL,
	constraint USERS_PK PRIMARY KEY ("UserID"));

CREATE TABLE "CUSTOMER" (
	"CustomerID" NUMBER(10,0) NOT NULL,
	"UserID" NUMBER(10,0) NOT NULL,
	"AddressID" NUMBER(10,0) NOT NULL,
	"FirstName" VARCHAR2(50) NOT NULL,
	"SecondName" VARCHAR2(50) NOT NULL,
	"Patronymic" VARCHAR2(50) NOT NULL,
	"DateOfBirth" DATE NOT NULL,
	"Email" VARCHAR2(50) NOT NULL,
	"PhoneNumber" VARCHAR2(50) NOT NULL,
	"Photo" BLOB NOT NULL,
	constraint CUSTOMER_PK PRIMARY KEY ("CustomerID"));

CREATE TABLE "ADDRESS" (
	"AddressID" NUMBER(10,0) NOT NULL,
	"City" VARCHAR2(50) NOT NULL,
	"Street" VARCHAR2(50) NOT NULL,
	"HouseNumber" VARCHAR2(50) NOT NULL,
	"Room" VARCHAR2(50) NOT NULL,
	constraint ADDRESS_PK PRIMARY KEY ("AddressID"));

CREATE TABLE "PRODUCT" (
	"ProductID" NUMBER(10,0) NOT NULL,
	"Name" VARCHAR2(50) NOT NULL,
	"Manufacturer" VARCHAR2(50) NOT NULL,
	"Price" INT NOT NULL,
	"Photo" BLOB NOT NULL,
	constraint PRODUCT_PK PRIMARY KEY ("ProductID"));

CREATE TABLE "OPTIONTYPE" (
	"OptionTypeID" NUMBER(10,0) NOT NULL,
	"OptionTypeName" VARCHAR2(50) NOT NULL,
	constraint OPTIONTYPE_PK PRIMARY KEY ("OptionTypeID"));

CREATE TABLE "OPTION" (
	"OptionID" NUMBER(10,0) NOT NULL,
	"OptionTypeID" NUMBER(10,0) NOT NULL,
	"OptionName" VARCHAR2(50) NOT NULL);

CREATE TABLE "PRODUCTOPTION" (
	"ProductOptionID" NUMBER(10,0) NOT NULL,
	"ProductID" NUMBER(10,0) NOT NULL,
	"OptionID" NUMBER(10,0) NOT NULL,
	"Value" VARCHAR2(50) NOT NULL,
	"Unit" VARCHAR2(50) NOT NULL,
	constraint PRODUCTOPTION_PK PRIMARY KEY ("ProductOptionID"));

CREATE TABLE "BASKET" (
	"BasketID" NUMBER(10,0) NOT NULL,
	"ProductID" NUMBER(10,0) NOT NULL,
	"CustomerID" NUMBER(10,0) NOT NULL,
	"Amount" INT NOT NULL,
	"Price" INT NOT NULL,
	constraint BASKET_PK PRIMARY KEY ("BasketID"));

CREATE TABLE "FAVORITE" (
	"FavoriteID" NUMBER(10,0) NOT NULL,
	"ProductID" NUMBER(10,0) NOT NULL,
	"CustomerID" NUMBER(10,0) NOT NULL,
	constraint FAVORITE_PK PRIMARY KEY ("FavoriteID"));

CREATE TABLE "ORDERHISTORY" (
	"OrderHistoryID" NUMBER(10,0) NOT NULL,
	"ProdcutID" NUMBER(10,0) NOT NULL,
	"CustomerID" NUMBER(10,0) NOT NULL,
	"Status" VARCHAR2(50) NOT NULL,
	"Date" DATE NOT NULL,
	"Amount" INT NOT NULL,
	"Price" INT NOT NULL,
	"KeyFindProduct" INT NOT NULL,
	constraint ORDERHISTORY_PK PRIMARY KEY ("OrderHistoryID"));

CREATE TABLE "REVIEW" (
	"ReviewID" NUMBER(10,0) NOT NULL,
	"ProductID" NUMBER(10,0) NOT NULL,
	"CustomerID" NUMBER(10,0) NOT NULL,
	"Discription" VARCHAR2(1000) NOT NULL,
	"Rating" INT NOT NULL,
	"Date" DATE NOT NULL,
	constraint REVIEW_PK PRIMARY KEY ("ReviewID"));

CREATE TABLE "PRODUCTCOMPRASION" (
	"ProductComparisonID" NUMBER(10,0) NOT NULL,
	"ProductID" NUMBER(10,0) NOT NULL,
	"CustomerID" NUMBER(10,0) NOT NULL,
	constraint PRODUCTCOMPRASION_PK PRIMARY KEY ("ProductComparisonID"));


ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_fk0" FOREIGN KEY ("UserID") REFERENCES "USERS"("UserID");
ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_fk1" FOREIGN KEY ("AddressID") REFERENCES "ADDRESS"("AddressID");
ALTER TABLE "OPTION" ADD CONSTRAINT "OPTION_fk0" FOREIGN KEY ("OptionTypeID") REFERENCES "OPTIONTYPE"("OptionTypeID");
ALTER TABLE "PRODUCTOPTION" ADD CONSTRAINT "PRODUCTOPTION_fk0" FOREIGN KEY ("ProductID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "PRODUCTOPTION" ADD CONSTRAINT "PRODUCTOPTION_fk1" FOREIGN KEY ("OptionID") REFERENCES "OPTION"("OptionID");
ALTER TABLE "BASKET" ADD CONSTRAINT "BASKET_fk0" FOREIGN KEY ("ProductID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "BASKET" ADD CONSTRAINT "BASKET_fk1" FOREIGN KEY ("CustomerID") REFERENCES "CUSTOMER"("CustomerID");
ALTER TABLE "FAVORITE" ADD CONSTRAINT "FAVORITE_fk0" FOREIGN KEY ("ProductID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "FAVORITE" ADD CONSTRAINT "FAVORITE_fk1" FOREIGN KEY ("CustomerID") REFERENCES "CUSTOMER"("CustomerID");
ALTER TABLE "ORDERHISTORY" ADD CONSTRAINT "ORDERHISTORY_fk0" FOREIGN KEY ("ProdcutID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "ORDERHISTORY" ADD CONSTRAINT "ORDERHISTORY_fk1" FOREIGN KEY ("CustomerID") REFERENCES "CUSTOMER"("CustomerID");
ALTER TABLE "REVIEW" ADD CONSTRAINT "REVIEW_fk0" FOREIGN KEY ("ProductID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "REVIEW" ADD CONSTRAINT "REVIEW_fk1" FOREIGN KEY ("CustomerID") REFERENCES "CUSTOMER"("CustomerID");
ALTER TABLE "PRODUCTCOMPRASION" ADD CONSTRAINT "PRODUCTCOMPRASION_fk0" FOREIGN KEY ("ProductID") REFERENCES "PRODUCT"("ProductID");
ALTER TABLE "PRODUCTCOMPRASION" ADD CONSTRAINT "PRODUCTCOMPRASION_fk1" FOREIGN KEY ("CustomerID") REFERENCES "CUSTOMER"("CustomerID");


CREATE sequence "USERS_USERID_SEQ";
CREATE sequence "CUSTOMER_CUSTOMERID_SEQ";
CREATE sequence "ADDRESS_ADDRESSID_SEQ";
CREATE sequence "PRODUCT_PRODUCTID_SEQ";
CREATE sequence "OPTIONTYPE_OPTIONTYPEID_SEQ";
CREATE sequence "PRODUCTOPTION_PRODUCTOPTIONID_SEQ";
CREATE sequence "BASKET_BASKETID_SEQ";
CREATE sequence "FAVORITE_FAVORITEID_SEQ";
CREATE sequence "ORDERHISTORY_ORDERHISTORYID_SEQ";
CREATE sequence "REVIEW_REVIEWID_SEQ";
CREATE sequence "PRODUCTCOMPRASION_PRODUCTCOMPARISONID_SEQ";



CREATE trigger "BI_USERS_USERID"
  before insert on "USERS"
  for each row
begin
  select "USERS_USERID_SEQ".nextval into :NEW."UserID" from dual;
end;
CREATE trigger "BI_CUSTOMER_CUSTOMERID"
  before insert on "CUSTOMER"
  for each row
begin
  select "CUSTOMER_CUSTOMERID_SEQ".nextval into :NEW."CustomerID" from dual;
end;
CREATE trigger "BI_ADDRESS_ADDRESSID"
  before insert on "ADDRESS"
  for each row
begin
  select "ADDRESS_ADDRESSID_SEQ".nextval into :NEW."AddressID" from dual;
end;
CREATE trigger "BI_PRODUCT_PRODUCTID"
  before insert on "PRODUCT"
  for each row
begin
  select "PRODUCT_PRODUCTID_SEQ".nextval into :NEW."ProductID" from dual;
end;
CREATE trigger "BI_OPTIONTYPE_OPTIONTYPEID"
  before insert on "OPTIONTYPE"
  for each row
begin
  select "OPTIONTYPE_OPTIONTYPEID_SEQ".nextval into :NEW."OptionTypeID" from dual;
end;
CREATE trigger "BI_PRODUCTOPTION_PRODUCTOPTIONID"
  before insert on "PRODUCTOPTION"
  for each row
begin
  select "PRODUCTOPTION_PRODUCTOPTIONID_SEQ".nextval into :NEW."ProductOptionID" from dual;
end;
CREATE trigger "BI_BASKET_BASKETID"
  before insert on "BASKET"
  for each row
begin
  select "BASKET_BASKETID_SEQ".nextval into :NEW."BasketID" from dual;
end;
CREATE trigger "BI_FAVORITE_FAVORITEID"
  before insert on "FAVORITE"
  for each row
begin
  select "FAVORITE_FAVORITEID_SEQ".nextval into :NEW."FavoriteID" from dual;
end;
CREATE trigger "BI_ORDERHISTORY_ORDERHISTORYID"
  before insert on "ORDERHISTORY"
  for each row
begin
  select "ORDERHISTORY_ORDERHISTORYID_SEQ".nextval into :NEW."OrderHistoryID" from dual;
end;
CREATE trigger "BI_REVIEW_REVIEWID"
  before insert on "REVIEW"
  for each row
begin
  select "REVIEW_REVIEWID_SEQ".nextval into :NEW."ReviewID" from dual;
end;
CREATE trigger "BI_PRODUCTCOMPRASION_PRODUCTCOMPARISONID"
  before insert on "PRODUCTCOMPRASION"
  for each row
begin
  select "PRODUCTCOMPRASION_PRODUCTCOMPARISONID_SEQ".nextval into :NEW."ProductComparisonID" from dual;
end;


