ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-------------------------------------------------APPUSER------------------------------------------------------------------------
DROP TABLESPACE TS_APPUSER;
CREATE TABLESPACE TS_APPUSER
       DATAFILE 'TS_APPUSER.dat'
       SIZE 10M 
       AUTOEXTEND ON;
       
DROP TABLESPACE TS_APPUSER_TEMP;
CREATE TEMPORARY TABLESPACE TS_APPUSER_TEMP 
        TEMPFILE 'TS_APPUSER_TEMP.dat' 
        SIZE 5M 
        AUTOEXTEND ON;
        
CREATE ROLE RL_APPUSER;
GRANT ALL PRIVILEGES TO RL_APPUSER;

CREATE PROFILE PF_APPUSER LIMIT
       PASSWORD_LIFE_TIME 180      
       SESSIONS_PER_USER 3         
       FAILED_LOGIN_ATTEMPTS 7     
       PASSWORD_LOCK_TIME 1       
       PASSWoRD_REUSE_TIME 10      
       PASSWORD_GRACE_TIME DEFAULT 
       CONNECT_TIME 180            
       IDLE_TIME 30; 
       
DROP USER APPUSER CASCADE;
CREATE USER APPUSER IDENTIFIED BY Pa$$w0rd
    DEFAULT TABLESPACE TS_APPUSER QUOTA UNLIMITED ON TS_APPUSER
    TEMPORARY TABLESPACE TS_APPUSER_TEMP 
    PROFILE PF_APPUSER;

GRANT RL_APPUSER TO APPUSER;
-------------------------------------------------APPADMIN------------------------------------------------------------------------
DROP TABLESPACE TS_APPADMIN;
CREATE TABLESPACE TS_APPADMIN
       DATAFILE 'TS_APPADMIN.dat'
       SIZE 10M 
       AUTOEXTEND ON;
       
DROP TABLESPACE TS_APPADMIN_TEMP;
CREATE TEMPORARY TABLESPACE TS_APPADMIN_TEMP 
        TEMPFILE 'TS_APPADMIN_TEMP.dat' 
        SIZE 5M 
        AUTOEXTEND ON;
        
CREATE ROLE RL_APPADMIN;
GRANT CREATE SESSION TO RL_APPADMIN;
GRANT EXECUTE ON ADMINADDCUSTOMER TO RL_APPADMIN;
GRANT EXECUTE ON ADMINADDOPTION TO RL_APPADMIN;      
GRANT EXECUTE ON ADMINADDPRODUCT TO RL_APPADMIN;
GRANT EXECUTE ON ADMINDELETECUSTOMER TO RL_APPADMIN;
GRANT EXECUTE ON ADMINDELETEOPTION TO RL_APPADMIN;
GRANT EXECUTE ON ADMINDELETEPRODUCT TO RL_APPADMIN;
GRANT EXECUTE ON ADMINUPDATECUSTOMER TO RL_APPADMIN;
GRANT EXECUTE ON ADMINUPDATEOPTION TO RL_APPADMIN;
GRANT EXECUTE ON ADMINUPDATEPRODUCT TO RL_APPADMIN;
GRANT EXECUTE ON LOGIN TO RL_APPADMIN;
GRANT EXECUTE ON REGISTEADMIN TO RL_APPADMIN;
GRANT EXECUTE ON REGISTERUSER TO RL_APPADMIN;
GRANT EXECUTE ON TABLE_TO_XML_FILE TO RL_APPADMIN;
GRANT EXECUTE ON SHOWCATALOG TO RL_APPADMIN;

CREATE PROFILE PF_APPADMIN LIMIT
       PASSWORD_LIFE_TIME 180      
       SESSIONS_PER_USER 3         
       FAILED_LOGIN_ATTEMPTS 7     
       PASSWORD_LOCK_TIME 1       
       PASSWoRD_REUSE_TIME 10      
       PASSWORD_GRACE_TIME DEFAULT 
       CONNECT_TIME 180            
       IDLE_TIME 30; 
       
DROP USER APPAPPADMIN CASCADE;
CREATE USER APPADMIN IDENTIFIED BY Pa$$w0rd
    DEFAULT TABLESPACE TS_APPADMIN QUOTA UNLIMITED ON TS_APPADMIN
    TEMPORARY TABLESPACE TS_APPADMIN_TEMP 
    PROFILE PF_APPADMIN;

GRANT RL_APPADMIN TO APPADMIN;
-------------------------------------------------APPCLIENT------------------------------------------------------------------------
DROP TABLESPACE TS_APPCLIENT;
CREATE TABLESPACE TS_APPCLIENT
       DATAFILE 'TS_APPCLIENT.dat'
       SIZE 10M 
       AUTOEXTEND ON;
       
DROP TABLESPACE TS_APPCLIENT_TEMP;
CREATE TEMPORARY TABLESPACE TS_APPCLIENT_TEMP 
        TEMPFILE 'TS_APPCLIENT_TEMP.dat' 
        SIZE 5M 
        AUTOEXTEND ON;
        
CREATE ROLE RL_APPCLIENT;
GRANT CREATE SESSION TO RL_APPCLIENT;
GRANT EXECUTE ON BASKETDELETEONE TO RL_APPCLIENT;
GRANT EXECUTE ON LOGIN TO RL_APPCLIENT;      
GRANT EXECUTE ON PERSONAINFOUPDATE TO RL_APPCLIENT;
GRANT EXECUTE ON PERSONALINFOSELECT TO RL_APPCLIENT;
GRANT EXECUTE ON REGISTERUSER TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWBASKET TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWCATALOG TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWFAVORITE TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWHISTORY TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWOPTIONPRODUCT TO RL_APPCLIENT;
GRANT EXECUTE ON SHOWREVIEW TO RL_APPCLIENT;


CREATE PROFILE PF_APPCLIENT LIMIT
       PASSWORD_LIFE_TIME 180      
       SESSIONS_PER_USER 3         
       FAILED_LOGIN_ATTEMPTS 7     
       PASSWORD_LOCK_TIME 1       
       PASSWoRD_REUSE_TIME 10      
       PASSWORD_GRACE_TIME DEFAULT 
       CONNECT_TIME 180            
       IDLE_TIME 30; 
       
DROP USER APPCLIENT CASCADE;
CREATE USER APPCLIENT IDENTIFIED BY Pa$$w0rd
    DEFAULT TABLESPACE TS_APPCLIENT QUOTA UNLIMITED ON TS_APPCLIENT
    TEMPORARY TABLESPACE TS_APPCLIENT_TEMP 
    PROFILE PF_APPCLIENT;

GRANT RL_APPCLIENT TO APPCLIENT;
-------------------------------------------------APPANONIM------------------------------------------------------------------------
DROP TABLESPACE TS_APPANONIM;
CREATE TABLESPACE TS_APPANONIM
       DATAFILE 'TS_APPANONIM.dat'
       SIZE 10M 
       AUTOEXTEND ON;
       
DROP TABLESPACE TS_APPANONIM_TEMP;
CREATE TEMPORARY TABLESPACE TS_APPANONIM_TEMP 
        TEMPFILE 'TS_APPANONIM_TEMP.dat' 
        SIZE 5M 
        AUTOEXTEND ON;
        
CREATE ROLE RL_APPANONIM;
GRANT CREATE SESSION TO RL_APPANONIM;
GRANT EXECUTE ON SHOWCATALOG TO RL_APPANONIM;
GRANT EXECUTE ON SHOWOPTIONPRODUCT TO RL_APPANONIM;
GRANT EXECUTE ON SHOWREVIEW TO RL_APPANONIM;



CREATE PROFILE PF_APPANONIM LIMIT
       PASSWORD_LIFE_TIME 180      
       SESSIONS_PER_USER 3         
       FAILED_LOGIN_ATTEMPTS 7     
       PASSWORD_LOCK_TIME 1       
       PASSWoRD_REUSE_TIME 10      
       PASSWORD_GRACE_TIME DEFAULT 
       CONNECT_TIME 180            
       IDLE_TIME 30; 
       
DROP USER APPANONIM CASCADE;
CREATE USER APPANONIM IDENTIFIED BY Pa$$w0rd
    DEFAULT TABLESPACE TS_APPANONIM QUOTA UNLIMITED ON TS_APPANONIM
    TEMPORARY TABLESPACE TS_APPANONIM_TEMP 
    PROFILE PF_APPANONIM;

GRANT RL_APPANONIM TO APPANONIM;


  
  
  
